[clog]
repository = "https://github.com/kbknapp/cargo-extras"
outfile = "CHANGELOG.md"
from-latest-tag = true

[sections]
Performance = ["perf"]
Improvements = ["impr", "im", "imp"]
Documentation = ["docs"]
Deprecations = ["depr"]
Examples = ["examples"]
Additions = ["add"]
